In [2]:
import numpy as np

In [2]:
np.__version__

'2.2.4'

## Create And Read

#### 1D array

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [10]:
arr1.size

5

## 2D Array

An array that contains multiple 1D arrays.

In [11]:
arr2 = np.array([[1,4,5],[6,7,4]])

In [12]:
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [13]:
arr2.ndim

2

In [19]:
arr2.shape # (row,col)

(2, 3)

In [20]:
arr2.dtype

dtype('int64')

In [21]:
arr2.size

6

## 3D Array

In [10]:
arr3 = np.array([[[1,4,5],[6,7,4]],[[6,3,5],[9,1,4]]])

In [23]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[6, 3, 5],
        [9, 1, 4]]])

In [24]:
arr3.ndim

3

In [26]:
arr3.shape 

(2, 2, 3)

In 3d array, (this is the number of layers that is the number of 2D arrays, this is the number of rows per layer,
              this is the number of columns per layer)

In [17]:
arr3 = np.array([[[1,4,5],[6,7,4],[1,4,5]],[[6,3,5],[9,1,4],[1,4,5]],[[1,4,5],[6,7,4],[1,4,5]]])

In [29]:
arr3

array([[[1, 4, 5],
        [6, 7, 4],
        [1, 4, 5]],

       [[6, 3, 5],
        [9, 1, 4],
        [1, 4, 5]],

       [[1, 4, 5],
        [6, 7, 4],
        [1, 4, 5]]])

In [34]:
arr3.shape

(3, 3, 3)

## Create random Array

In [31]:
randomArr = np.random.rand(2,3,4)

In [32]:
randomArr

array([[[0.66041142, 0.26743415, 0.94598079, 0.80418878],
        [0.69306417, 0.00428703, 0.16476854, 0.85459005],
        [0.46997543, 0.25328766, 0.9729495 , 0.99455942]],

       [[0.33871526, 0.39557832, 0.57788872, 0.73090091],
        [0.11587551, 0.68965691, 0.56828994, 0.62110698],
        [0.60624732, 0.67045758, 0.76812273, 0.90891387]]])

In [37]:
randomArr2 = np.random.rand(4,3,4)

In [39]:
randomArr2

array([[[0.11644145, 0.95552638, 0.71000563, 0.71199808],
        [0.44537722, 0.04069795, 0.72124462, 0.83845103],
        [0.82580444, 0.85960606, 0.67249275, 0.49181535]],

       [[0.02428953, 0.41058964, 0.00597271, 0.1704504 ],
        [0.60163917, 0.76829583, 0.14830292, 0.14354946],
        [0.53554139, 0.33848695, 0.06049446, 0.92279671]],

       [[0.73478987, 0.51699351, 0.01589619, 0.90635244],
        [0.15503548, 0.7557587 , 0.73054502, 0.64479447],
        [0.11027403, 0.97408844, 0.53139019, 0.49973111]],

       [[0.88692735, 0.63714561, 0.675631  , 0.55610185],
        [0.0361364 , 0.18518628, 0.85113179, 0.93143803],
        [0.22713511, 0.19431932, 0.6985038 , 0.69521619]]])

In [40]:
randomArr.dtype

dtype('float64')

In [41]:
type(randomArr)

numpy.ndarray

In [35]:
randomArr3 = np.zeros((2,3,4))

In [44]:
randomArr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [45]:
randomArr3.ndim

3

In [46]:
randomArr4 = np.full((2,3,4),7)

In [47]:
randomArr4

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [48]:
ones = np.ones(((2,3,4)))

In [49]:
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
arr3

array([[[1, 4, 5],
        [6, 7, 4],
        [1, 4, 5]],

       [[6, 3, 5],
        [9, 1, 4],
        [1, 4, 5]],

       [[1, 4, 5],
        [6, 7, 4],
        [1, 4, 5]]])

In [51]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4],
       [1, 4, 5]])

In [52]:
arr3[2]

array([[1, 4, 5],
       [6, 7, 4],
       [1, 4, 5]])

In [54]:
arr3[2][1]

array([6, 7, 4])

In [55]:
arr3[2][1][2]

np.int64(4)

In [56]:
arr3[2,1,2]

np.int64(4)

## Update And Delete

In [57]:
arr1 = np.random.rand(2,3,2)

In [58]:
arr1

array([[[0.71965349, 0.34430159],
        [0.21120199, 0.66051065],
        [0.88856149, 0.29838514]],

       [[0.71664498, 0.47265705],
        [0.8287584 , 0.9538925 ],
        [0.92760723, 0.51009644]]])

In [59]:
arr2 = np.random.rand(2,3,2)

In [60]:
arr2

array([[[0.5823643 , 0.87894367],
        [0.48547646, 0.76073685],
        [0.63201169, 0.48126641]],

       [[0.341006  , 0.83064719],
        [0.01598278, 0.51130429],
        [0.78579832, 0.01877785]]])

#### Basic math operations

In [63]:
np.add(arr1,arr2)

array([[[1.30201778, 1.22324526],
        [0.69667845, 1.42124751],
        [1.52057317, 0.77965155]],

       [[1.05765098, 1.30330424],
        [0.84474118, 1.46519679],
        [1.71340555, 0.52887429]]])

In [64]:
np.subtract(arr1,arr2)

array([[[ 0.13728919, -0.53464208],
        [-0.27427447, -0.1002262 ],
        [ 0.2565498 , -0.18288128]],

       [[ 0.37563899, -0.35799014],
        [ 0.81277562,  0.44258821],
        [ 0.14180891,  0.4913186 ]]])

In [65]:
np.divide(arr1,arr2)

array([[[ 1.23574451,  0.39172202],
        [ 0.43504064,  0.86825115],
        [ 1.40592572,  0.61999992]],

       [[ 2.10156123,  0.56902263],
        [51.85319943,  1.86560629],
        [ 1.18046477, 27.16480181]]])

In [66]:
np.multiply(arr1,arr2)

array([[[0.4191005 , 0.30262171],
        [0.10253359, 0.5024748 ],
        [0.56158124, 0.14360274]],

       [[0.24438024, 0.39261125],
        [0.01324587, 0.48772933],
        [0.7289122 , 0.00957851]]])

#### Statistical Operations

In [67]:
squareRoot = np.sqrt(49)

In [68]:
squareRoot

np.float64(7.0)

In [3]:
absoluteValue = np.abs(-55)

In [4]:
absoluteValue

np.int64(55)

In [5]:
power = np.power(2,3)

In [6]:
power

np.int64(8)

In [7]:
log = np.log(25)

In [8]:
log

np.float64(3.2188758248682006)

In [11]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[6, 3, 5],
        [9, 1, 4]]])

In [12]:
minimum = np.min(arr3)

In [13]:
minimum

np.int64(1)

In [14]:
maximum = np.max(arr3)

In [15]:
maximum

np.int64(9)

## Update elements in array

In [18]:
arr3

array([[[1, 4, 5],
        [6, 7, 4],
        [1, 4, 5]],

       [[6, 3, 5],
        [9, 1, 4],
        [1, 4, 5]],

       [[1, 4, 5],
        [6, 7, 4],
        [1, 4, 5]]])

In [19]:
arr3[0,0,2] = 500

In [20]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4],
        [  1,   4,   5]],

       [[  6,   3,   5],
        [  9,   1,   4],
        [  1,   4,   5]],

       [[  1,   4,   5],
        [  6,   7,   4],
        [  1,   4,   5]]])

In [21]:
arr3.sort()

In [22]:
arr3

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  1,   4,   5]],

       [[  3,   5,   6],
        [  1,   4,   9],
        [  1,   4,   5]],

       [[  1,   4,   5],
        [  4,   6,   7],
        [  1,   4,   5]]])

In [23]:
arr3.shape

(3, 3, 3)

#### Reshape array 

In [28]:
array = np.random.rand(2,3,2)

In [29]:
array

array([[[0.21677598, 0.63593205],
        [0.40149731, 0.37372374],
        [0.68828335, 0.50894114]],

       [[0.0146127 , 0.76667176],
        [0.99779462, 0.17892392],
        [0.10044403, 0.4167132 ]]])

In [30]:
array.shape

(2, 3, 2)

In [33]:
array.reshape(2,2,3) # 2*3*2 = 2*2*3 = 12

array([[[0.21677598, 0.63593205, 0.40149731],
        [0.37372374, 0.68828335, 0.50894114]],

       [[0.0146127 , 0.76667176, 0.99779462],
        [0.17892392, 0.10044403, 0.4167132 ]]])

### Appending And inserting

In [52]:
zeroes = np.zeros((3,2,3))

In [53]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
newArray = np.ones((3, 2, 3))

In [55]:
newArray

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
append = np.append(zeroes,newArray,axis = 1)

In [57]:
append

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [58]:
append = np.append(zeroes,newArray,axis = 0)

In [59]:
append

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
insert = np.insert(zeroes,2,newArray,axis=0)

In [63]:
insert

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Delete

In [64]:
arr4 = np.random.rand(3,2,3)

In [65]:
arr4

array([[[0.98306077, 0.5799525 , 0.60747172],
        [0.01409199, 0.10097156, 0.37598779]],

       [[0.18477931, 0.1408316 , 0.38202659],
        [0.97814808, 0.46909365, 0.1948998 ]],

       [[0.10191218, 0.90842797, 0.70598963],
        [0.34753391, 0.17991348, 0.61279281]]])

In [68]:
arr5 = np.delete(arr4,0,axis=1)

In [69]:
arr5

array([[[0.01409199, 0.10097156, 0.37598779]],

       [[0.97814808, 0.46909365, 0.1948998 ]],

       [[0.34753391, 0.17991348, 0.61279281]]])

In [70]:
np.save("new_array",arr5)

In [71]:
np.load("new_array.npy")

array([[[0.01409199, 0.10097156, 0.37598779]],

       [[0.97814808, 0.46909365, 0.1948998 ]],

       [[0.34753391, 0.17991348, 0.61279281]]])